### ISSUE TITLE
Hardcore Ender Expansion and TE Interaction Bug

### ISSUE THREAD

**Issue by AshtenD** [TPPIDev/TestPackPleaseIgnore#270]
Stardust in hardcore ender can be used to uncraft items. If you use this on a Hardened Energy Cell, it pops out a Redstone Energy Cell and a random amount of Enderium Ingots.  

To do this, place Stardust on the ground (like redstone) and then throw the Hardened Energy Cell on top of it and give it a few seconds. It will break down. I believe the amount of Enderium you get is based on the Cell's charge. With an Empty one I got 2.

**Comment by chylex** [comment]
The issue is severely outdated and even if the bug was confirmed (it doesn't sound like a bug to me, but I haven't done much TE), 1.6.4 won't ever have any more updates.
