### ISSUE TITLE
TPPI Server crashes during startup.

### ISSUE THREAD

**Issue by dmsdjing** [TPPIDev/TestPackPleaseIgnore#566]
Hello, every time I go to start the Test Pack Please Ignore server I get the following crash report in my server files. Here is a pastebin link. http://pastebin.com/6fBdq5P8 I have updated Java to JRE 7_71u and my operating system is CentOS. 

Thanks in advance.

**Comment by Aron23629** [comment]
I log in normal and it goes to the "Mojang" starting screen, but instead of going to the start-up menu, it just Xes me out and goes back to the launcher. What should I do?

**Comment by dmsdjing** [comment]
I have no clue. The issue that I solved was for a server.

---
This email has been checked for viruses by Avast antivirus software.
http://www.avast.com

**Comment by TehNut** [comment]
@Aron23629 
1. This is not related to this issue at all. You should have created your own.

2. Read through [this](http://pastebin.com/9rjFNN8v)

Since OP said it's fixed, I will close it.
