### ISSUE TITLE
Crash on Mojang Screen

### ISSUE THREAD

**Issue by Cbabbs99** [TPPIDev/TestPackPleaseIgnore#628]
I click play on TPPI from launcher and the Mojang screen displays for a while and it suddenly crashes. I'm using recommended version with 4 GBs of memory allocated as well as Java 7. Heres the crash report:

http://pastebin.com/raw.php?i=e6fZ2idR

Any help would be great, thanks!

**Comment by TehNut** [comment]
You're using Java 6. Upgrade it.

**Comment by Cbabbs99** [comment]
Okay so I just tried to reinstall Java 7 and it still crashed. Heres the new crash report:
http://pastebin.com/raw.php?i=v6ewi97h

**Comment by TehNut** [comment]
That's the same thing. Please read your log.

>Java Version: 1.6.0_65, Apple Inc.

**Comment by Cbabbs99** [comment]
Well I uninstalled the Java version I was using before and reinstalled Java 7 from this link: https://java.com/en/download/manual_java7.jsp

I tried playing again and the crash report it gave me was the one I posted in the comment above and I just tried it again and it gave me this one:
http://pastebin.com/raw.php?i=R5rRirqk

**Comment by Cbabbs99** [comment]
Where can I get the correct Java 7?

**Comment by Cbabbs99** [comment]
I do see now where it says I'm using Java 6 in the crash report but I swear I uninstalled that version and reinstalled Java 7 from the link I gave you
