### ISSUE TITLE
crash on tppi

### ISSUE THREAD

**Issue by justin348** [TPPIDev/TestPackPleaseIgnore#631]
---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 1/21/15 7:24 AM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.ClassNotFoundException: codechicken.enderstorage.EnderStorage
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:156)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:521)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:183)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:473)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:808)
	at net.minecraft.client.main.Main.main(SourceFile:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
Caused by: java.lang.ClassNotFoundException: codechicken.enderstorage.EnderStorage
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:186)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at cpw.mods.fml.common.ModClassLoader.loadClass(ModClassLoader.java:61)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:249)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:462)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
	at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
	at com.google.common.eventbus.EventBus.post(EventBus.java:267)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:201)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:181)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
	at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
	at com.google.common.eventbus.EventBus.post(EventBus.java:267)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:112)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:511)
	... 10 more
Caused by: java.lang.UnsupportedClassVersionError: codechicken/enderstorage/EnderStorage : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:178)
	... 37 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.6.4
	Operating System: Mac OS X (x86_64) version 10.9.5
	Java Version: 1.6.0_65, Apple Inc.
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
	Memory: 126241128 bytes (120 MB) / 381136896 bytes (363 MB) up to 1601896448 bytes (1527 MB)
	JVM Flags: 2 total; -Xmx1536m -XX:MaxPermSize=128m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Suspicious classes: FML and Forge are installed
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v8.11 FML v6.4.49.965 Minecraft Forge 9.11.1.965 181 mods loaded, 181 mods active
	mcp{8.09} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed
	FML{6.4.49.965} [Forge Mod Loader] (modpack.jar) Unloaded->Constructed
	Forge{9.11.1.965} [Minecraft Forge] (modpack.jar) Unloaded->Constructed
	denLib{3.2.6} [denLib] (minecraft.jar) Unloaded->Constructed
	InfiniBows{1.2.0 build 14} [Infinity Bow Fix] (minecraft.jar) Unloaded->Constructed
	MobiusCore{1.2.2} [MobiusCore] (minecraft.jar) Unloaded->Constructed
	AM2-Preloader{0.0.1} [AMCore] (minecraft.jar) Unloaded->Constructed
	AppliedEnergistics-Core{rv14.finale3} [AppliedEnergistics Core] (minecraft.jar) Unloaded->Constructed
	CodeChickenCore{0.9.0.9} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed
	Evoc{1.0.0} [Evoc] (minecraft.jar) Unloaded->Constructed
	ImmibisMicroblocks{57.6.3} [Immibis's Microblocks] (immibis-microblocks-57.6.3.jar) Unloaded->Constructed
	NotEnoughItems{1.6.1.9} [Not Enough Items] (notenoughitems 1.6.1.9.jar) Unloaded->Constructed
	OpenEye{0.6} [OpenEye] (openeye-0.6-1.6.4.jar) Unloaded->Constructed
	PowerCrystalsCore{1.1.8} [PowerCrystals Core] (powercrystalscore-1.1.8-9.jar) Unloaded->Constructed
	TConstruct-Preloader{0.0.1} [Tinkers Corestruct] (minecraft.jar) Unloaded->Constructed
	OpenModsCore{@VERSION@} [OpenModsCore] (minecraft.jar) Unloaded->Constructed
	DenEvents{1.0} [DenEvents] (DenEvents.jar) Unloaded->Constructed
	advancedgenetics{v1.4.2} [Advanced Genetics] (advgen.zip) Unloaded->Constructed
	AnimationAPI{1.1.1} [AnimationAPI] (animationapi v1.1.2 mc1.6.4.zip) Unloaded->Constructed
	arsmagica2{1.2.0.022} [Ars Magica 2] (am2_1.2.0.022.jar) Unloaded->Constructed
	AppliedEnergistics{rv14.finale3} [Applied Energistics] (appeng-rv14-finale3-mc16x.jar) Unloaded->Constructed
	bspkrsCore{v5.3(1.6.4)} [bspkrsCore] (bspkrscorev5.3.zip) Unloaded->Constructed
	ArmorStatusHUD{v1.15(1.6.4)} [ArmorStatusHUD] (armorstatushudv1.15.zip) Unloaded->Constructed
	Autoutils{1.0.1} [Autoutils] (autoutils-1.6.4-1.0.1.jar) Unloaded->Constructed
	bdlib{1.2.3.48} [BD Lib] (Bdlib-mc164-1.2.3.48.jar) Unloaded->Constructed
	BiblioCraft{1.5.5} [BiblioCraft] (bibliocraft[v1.5.5].zip) Unloaded->Constructed
	Natura{2.1.14} [Natura] (natura_mc1.6.X_2.1.14.jar) Unloaded->Constructed
	BiomesOPlenty{1.2.1} [Biomes O' Plenty] (biomesoplenty-universal-1.6.4-1.2.1.416.jar) Unloaded->Constructed
	BiblioWoodsBoP{1.3} [BiblioWoods Biomes O'Plenty Edition] (bibliowoods[biomesoplenty][v1.3].zip) Unloaded->Constructed
	CoFHCore{2.0.0.5} [CoFH Core] (cofhcore-2.0.0.5.jar) Unloaded->Constructed
	NetherOres{1.6.2R2.2.1} [Nether Ores] (NetherOres-2.2.1-14.jar) Unloaded->Constructed
	BuildCraft|Core{4.2.2} [BuildCraft] (BUILDCRAFT-A-1.6.4-4.2.2.jar) Unloaded->Constructed
	UniversalElectricity{3.1.0} [Universal Electricity] (Universal-Electricity-3.1.0.115-core.jar) Unloaded->Constructed
	ForgeMultipart{1.0.0.250} [Forge Multipart] (ForgeMultipart-universal-1.6.4-1.0.0.250.jar) Unloaded->Constructed
	ThermalExpansion{3.0.0.7} [Thermal Expansion] (thermalexpansion-3.0.0.7.jar) Unloaded->Constructed
	IC2{2.0.397-experimental} [IndustrialCraft 2] (Industrialcraft-2_2.0.397-experimental.jar) Unloaded->Constructed
	BuildCraft|Builders{4.2.2} [BC Builders] (BUILDCRAFT-A-1.6.4-4.2.2.jar) Unloaded->Constructed
	BuildCraft|Energy{4.2.2} [BC Energy] (BUILDCRAFT-A-1.6.4-4.2.2.jar) Unloaded->Constructed
	BuildCraft|Factory{4.2.2} [BC Factory] (BUILDCRAFT-A-1.6.4-4.2.2.jar) Unloaded->Constructed
	BuildCraft|Transport{4.2.2} [BC Transport] (BUILDCRAFT-A-1.6.4-4.2.2.jar) Unloaded->Constructed
	MineFactoryReloaded{1.6.4R2.7.8} [MineFactory Reloaded] (minefactoryreloaded-2.7.8-482.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatForestryPre{1.6.4R2.7.8} [MFR Compat: Forestry (part 2)] (minefactoryreloaded-2.7.8-482.jar) Unloaded->Constructed
	Forestry{2.3.1.1} [Forestry for Minecraft] (forestry-A-2.3.1.1.jar) Unloaded->Constructed
	BiblioWoodsForestry{1.3} [BiblioWoods Forestry Edition] (BiblioWoods[Forestry][v1.3].zip) Unloaded->Constructed
	BiblioWoodsNatura{1.1} [BiblioWoods Natura Edition] (bibliowoods[natura][v1.1].zip) Unloaded->Constructed
	ComputerCraft{1.63} [ComputerCraft] (computercraft1.63.jar) Unloaded->Constructed
	Mekanism{6.1.5.TPPI} [Mekanism] (Mekanism-6.1.5.TPPI.jar) Unloaded->Constructed
	BigReactors{0.3.4A2} [Big Reactors] (BigReactors-0.3.4A2.jar) Unloaded->Constructed
	BinnieCore{1.8.0} [Binnie Core] (Binnie-mods-1.8.0.jar) Unloaded->Constructed
	ExtraBees{1.8.0} [Extra Bees] (Binnie-mods-1.8.0.jar) Unloaded->Constructed
	ExtraTrees{1.8.0} [Extra Trees] (Binnie-mods-1.8.0.jar) Unloaded->Constructed
	AWWayofTime{v1.0.1g} [Blood Magic: Alchemical Wizardry] (Blood Magic v1.0.1g.zip) Unloaded->Constructed
	Botania{beta-16} [Botania] (Botania beta-16.jar) Unloaded->Constructed
	BuildCraft|Silicon{4.2.2} [BC Silicon] (BUILDCRAFT-A-1.6.4-4.2.2.jar) Unloaded->Constructed
	Additional-Buildcraft-Objects{1.0.7.558} [Additional Buildcraft Objects] (buildcraft-Z-additional-buildcraft-objects-1.0.7.558.jar) Unloaded->Constructed
	Thaumcraft{4.1.0g} [Thaumcraft] (Thaumcraft4.1.0g.zip) Unloaded->Constructed
	Railcraft{8.4.0.0} [Railcraft] (railcraft_1.6.4-8.4.0.0.jar) Unloaded->Constructed
	buildcraftAddon{1.6.4_v0.3.3} [BuildCraftAddon] (BuildcraftAddon-1.6.4_0.3.4.jar) Unloaded->Constructed
	CarpentersBlocks{3.2.8} [Carpenter's Blocks] (Carpenter's Blocks v3.2.8 - MC 1.6.4.jar) Unloaded->Constructed
	Chisel{1.5.2} [Chisel] (Chisel-1.5.2.jar) Unloaded->Constructed
	CoFHLoot{2.0.0.5} [CoFH Loot] (cofhcore-2.0.0.5.jar) Unloaded->Constructed
	CoFHMasquerade{2.0.0.5} [CoFH Masquerade] (cofhcore-2.0.0.5.jar) Unloaded->Constructed
	CoFHSocial{2.0.0.5} [CoFH Social] (cofhcore-2.0.0.5.jar) Unloaded->Constructed
	CoFHWorld{2.0.0.5} [CoFH World] (cofhcore-2.0.0.5.jar) Unloaded->Constructed
	DamageIndicatorsMod{2.9.2.3} [Damage Indicators] (damageindicatorsv2.9.2.3.zip) Unloaded->Constructed
	EnderStorage{1.4.3.6} [EnderStorage] (enderstorage 1.4.3.6.jar) Unloaded->Errored
	factorization{0.8.34} [Factorization] (Factorization-0.8.34.jar) Unloaded->Constructed
	gregtech_addon{MC162} [GregTech-Addon] (Gregtechmod 4.07o.zip) Unloaded->Constructed
	TwilightForest{1.20.3} [The Twilight Forest] (Twilightforest-1.20.3.jar) Unloaded->Constructed
	DartCraft{Beta 0.2.20} [DartCraft] (DartCraft Beta 0.2.20v2.jar) Unloaded->Constructed
	ImmibisCore{57.2.0} [Immibis Core] (immibis-core-57.2.0.jar) Unloaded->Constructed
	DimensionalAnchors{57.1.96} [Dimensional Anchors] (Dimensional-anchor-57.1.96.jar) Unloaded->Constructed
	eirairc{1.7.3} [EiraIRC] (Eirairc-mc1.6.4-v1.7.3.jar) Unloaded->Constructed
	Tombenpotter's Electro-Magic Tools{1.0.9} [Electro-Magic Tools] (ElectroMagicTools-1.0.9e.TPPI.jar) Unloaded->Constructed
	emashercore{1.2.3.4} [Emasher Resource] (EmasherResource-1.2.3.5.zip) Unloaded->Constructed
	EnderIO{1.0.2} [Ender IO] (EnderIO-1.6.4-1.0.2.363.jar) Unloaded->Constructed
	enderprospecting{1.0.1.6} [Ender Prospecting] (EnderProspecting1.0.1.6-1.6.4.zip) Unloaded->Constructed
	eng_toolbox{1.1.8.3} [Engineer's Toolbox] (EngineersToolbox-1.1.8.4.zip) Unloaded->Constructed
	LogisticsPipes|Main{0.7.4.dev.294} [Logistics Pipes] (LogisticsPipes-MC1.6.4-0.7.4.dev.294.jar) Unloaded->Constructed
	Waila{1.5.2a} [Waila] (waila_1.5.2a.zip) Unloaded->Constructed
	extracells{1.6.9b} [ExtraCells] (ExtraCells-1.6.9b.jar) Unloaded->Constructed
	ExtraUtilities{1.0.3c} [Extra Utilities] (extrautils-1.0.3c.zip) Unloaded->Constructed
	factorization.misc{0.8.34} [Factorization Miscellaneous Nonsense] (Factorization-0.8.34.jar) Unloaded->Constructed
	factorization.notify{0.8.34} [Factorization Notification System] (Factorization-0.8.34.jar) Unloaded->Constructed
	factorization.dimensionalSlice{0.8.34} [Factorization Dimensional Slices] (Factorization-0.8.34.jar) Unloaded->Constructed
	flatsigns{1.4.0} [Flat Signs] (Flatsigns-1.6.2-universal-1.4.0.15.jar) Unloaded->Constructed
	ThaumicTinkererKami{1.0} [Thaumic Tinkerer KAMI] (ThaumicTinkererKAMI_j6.jar) Unloaded->Constructed
	JABBA{1.1.4} [JABBA] (JABBA_1.1.4.zip) Unloaded->Constructed
	magicalcrops{3.2.1} [Magical Crops] (Magical_crops_1.6.4_3.2.0_BETA_15a.zip) Unloaded->Constructed
	numina{0.1.2-55} [Numina] (Numina-1.6.2-0.1.2-55.jar) Unloaded->Constructed
	powersuits{0.10.0-92} [MachineMuse's Modular Powersuits] (ModularPowersuits-1.6.4-0.10.0-92.jar) Unloaded->Constructed
	powersuitaddons{@VERSION@} [Andrew's Modular Powersuits Addons] (powersuitaddons-1.6.4-884.jar) Unloaded->Constructed
	ProjRed|Core{4.3.5.30} [ProjectRed] (ProjectRedBase-1.6.4-4.3.5.30.jar) Unloaded->Constructed
	recipeTweakingCore{1.0.0} [Recipe Tweaking Core] (RecipeTweakingCore-MC1.6.4-1.0.0-5.jar) Unloaded->Constructed
	xreliquary{1.6.4} [Xeno's Reliquary] (Reliquary-1.6.4-1.1-TPPI.jar) Unloaded->Constructed
	StevesFactoryManager{A83} [Steve's Factory Manager] (StevesFactoryManagerA83.zip) Unloaded->Constructed
	TPPITweaks{1.1.0} [TPPI Tweaks] (TPPI-Tweaks-MC1.6.4-1.1.0-103.jar) Unloaded->Constructed
	ThaumicTinkerer{2.3-140} [Thaumic Tinkerer] (ThaumicTinkerer-2.3-140.jar) Unloaded->Constructed
	ForbiddenMagic{0.35a} [Forbidden Magic] (ForbiddenMagic pr0.35a.jar) Unloaded->Constructed
	gendustry{1.1.3.78} [GenDustry] (Gendustry-mc164-1.1.3.78.jar) Unloaded->Constructed
	HardcoreEnderExpansion{1.5} [Hardcore Ender Expansion] (HardcoreEnderExpansion.zip) Unloaded->Constructed
	IC2NuclearControl{1.6.2e} [Nuclear Control] (IC2NuclearControl-1.6.2e-ic2-experimental.zip) Unloaded->Constructed
	iChunUtil{2.4.0} [iChunUtil] (ichunutil2.4.0.zip) Unloaded->Constructed
	InfernalMobs{1.4.4} [Infernal Mobs] (infernalmobs_1.6.4.zip) Unloaded->Constructed
	inventorytweaks{1.57-dev} [Inventory Tweaks] (InventoryTweaks-MC1.6.4-1.57-dev-b86.jar) Unloaded->Constructed
	IronChest{5.4.1.702} [Iron Chest] (ironchest-universal-1.6.4-5.4.1.702.zip) Unloaded->Constructed
	standardcrops{1.1.0} [Magical Crops - Crops & Food] (Magical_crops_1.6.4_3.2.0_BETA_15a.zip) Unloaded->Constructed
	TConstruct{1.6.X_1.5.5.7} [Tinkers' Construct] (tconstruct_mc1.6.4_1.5.5.7.jar) Unloaded->Constructed
	MagicBees{2.1.11} [Magic Bees] (Magicbees-2.1.11.jar) Unloaded->Constructed
	MekanismGenerators{6.1.2.TPPI} [MekanismGenerators] (MekanismGenerators-6.1.5.TPPI.jar) Unloaded->Constructed
	MFR Compat Forestry Trees{1.0} [MFR Compat Forestry Trees] (minefactoryreloaded-2.7.8-482.jar) Unloaded->Constructed
	MFR Compat Extra Trees{1.0} [MFR Compat Extra Trees] (minefactoryreloaded-2.7.8-482.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatAppliedEnergistics{1.6.4R2.7.8} [MFR Compat: Applied Energistics] (minefactoryreloaded-2.7.8-482.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatAtum{1.6.4R2.7.8} [MFR Compat: Atum] (minefactoryreloaded-2.7.8-482.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatBackTools{1.6.4R2.7.8} [MFR Compat: BackTools] (minefactoryreloaded-2.7.8-482.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatBuildCraft{1.6.4R2.7.8} [MFR Compat: BuildCraft] (minefactoryreloaded-2.7.8-482.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatChococraft{1.6.4R2.7.8} [MFR Compat: Chococraft] (minefactoryreloaded-2.7.8-482.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatExtraBiomes{1.6.4R2.7.8} [MFR Compat: ExtraBiomes] (minefactoryreloaded-2.7.8-482.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatForestry{1.6.4R2.7.8} [MFR Compat: Forestry] (minefactoryreloaded-2.7.8-482.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatForgeMicroblock{1.6.4R2.7.8} [MFR Compat: ForgeMicroblock] (minefactoryreloaded-2.7.8-482.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatIC2{1.6.4R2.7.8} [MFR Compat: IC2] (minefactoryreloaded-2.7.8-482.jar) Unloaded->Constructed
	Mystcraft{0.10.12.01} [Mystcraft] (mystcraft-uni-1.6.4-0.10.12.01.zip) Unloaded->Constructed
	MineFactoryReloaded|CompatMystcraft{1.6.4R2.7.8} [MFR Compat: Mystcraft] (minefactoryreloaded-2.7.8-482.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatPams{1.6.4R2.7.8} [MFR Compat: Pam's Mods] (minefactoryreloaded-2.7.8-482.jar) Unloaded->Constructed
	ProjRed|Exploration{4.3.5.30} [ProjectRed-Exploration] (ProjectRedWorld-1.6.4-4.3.5.30.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatProjRed{1.6.4R2.7.8} [MFR Compat ProjectRed] (minefactoryreloaded-2.7.8-482.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatRailcraft{1.6.4R2.7.8} [MFR Compat: Railcraft] (minefactoryreloaded-2.7.8-482.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatRP2{1.6.4R2.7.8} [MFR Compat: RP2] (minefactoryreloaded-2.7.8-482.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatSufficientBiomes{1.6.4R2.7.8} [MFR Compat: Sufficient Biomes] (minefactoryreloaded-2.7.8-482.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatThaumcraft{1.6.4R2.7.8} [MFR Compat: Thaumcraft] (minefactoryreloaded-2.7.8-482.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatThermalExpansion{1.6.4R2.7.8} [MFR Compat: Thermal Expansion] (minefactoryreloaded-2.7.8-482.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatTwilightForest{1.6.4R2.7.8} [MFR Compat: TwilightForest] (minefactoryreloaded-2.7.8-482.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatVanilla{1.6.4R2.7.8} [MFR Compat: Vanilla] (minefactoryreloaded-2.7.8-482.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatXyCraft{1.6.4R2.7.8} [MFR Compat: XyCraft] (minefactoryreloaded-2.7.8-482.jar) Unloaded->Constructed
	AdvancedSolarPanel{3.4.7} [Advanced Solar Panels] (Mod_AdvancedSolarPanels_3_4_7_IC_EXP.zip) Unloaded->Constructed
	GraviSuite{1.9.9a} [Gravitation Suite] (Mod_zGraviSuite_1_9_9a_MC_1_6_4_IC_EXP.zip) Unloaded->Constructed
	modpackTweaks{0.1.0} [ModpackTweaks] (ModpackTweaks-MC1.6.4-1.1.0-17.jar) Unloaded->Constructed
	ResonantEngine{@MAJOR@.@MINOR@.@REVIS@} [ResonantEngine] (Resonant-Engine-Development-1.2.0.266-universal.jar) Unloaded->Constructed
	MFFS{3.6.3} [Modular Force Field System] (Modular-Force-Field-System-3.6.3.91-core.jar) Unloaded->Constructed
	Morph{0.7.0} [Morph] (morphbeta-0.7.0.zip) Unloaded->Constructed
	NEIAddons{1.10.5.70} [NEI Addons] (Neiaddons-mc164-1.10.5.70.jar) Unloaded->Constructed
	NEIAddons|AE{1.10.5.70} [NEI Addons: Applied Energistics] (Neiaddons-mc164-1.10.5.70.jar) Unloaded->Constructed
	NEIAddons|MiscPeripherals{1.10.5.70} [NEI Addons: Misc Peripherals] (Neiaddons-mc164-1.10.5.70.jar) Unloaded->Constructed
	NEIAddons|ExtraBees{1.10.5.70} [NEI Addons: Extra Bees] (Neiaddons-mc164-1.10.5.70.jar) Unloaded->Constructed
	NEIAddons|Forestry{1.10.5.70} [NEI Addons: Forestry] (Neiaddons-mc164-1.10.5.70.jar) Unloaded->Constructed
	NEIAddons|CraftingTables{1.10.5.70} [NEI Addons: Crafting Tables] (Neiaddons-mc164-1.10.5.70.jar) Unloaded->Constructed
	NEIAddons|ExNihilo{1.10.5.70} [NEI Addons: Ex Nihilo] (Neiaddons-mc164-1.10.5.70.jar) Unloaded->Constructed
	NEIPlugins{1.1.0.6} [NEI Plugins] (neiplugins-1.1.0.6.jar) Unloaded->Constructed
	NotEnoughCodecs{0.1} [NotEnoughCodecs] (notenoughcodecs-0.1.jar) Unloaded->Constructed
	notenoughkeys{0.0.4} [Not Enough Keys] (notenoughkeys-1.6.4-0.0.4.jar) Unloaded->Constructed
	ObsidiPlates{2.0.0} [Obsidian Pressure Plates] (obsidiplates-1.6.2-universal-2.0.0.15.jar) Unloaded->Constructed
	OpenMods{0.5.1} [OpenMods] (openmodslib-0.5.1.jar) Unloaded->Constructed
	ProjRed|Transmission{4.3.5.30} [ProjectRed-Transmission] (ProjectRedIntegration-1.6.4-4.3.5.30.jar) Unloaded->Constructed
	OpenPeripheralCore{0.4.1} [OpenPeripheralCore] (openperipheralcore-0.4.1.jar) Unloaded->Constructed
	OpenPeripheral{0.1.5} [OpenPeripheralAddons] (openperipheraladdons-0.1.5.jar) Unloaded->Constructed
	OpenBlocks{1.2.9} [OpenBlocks] (openblocks-1.2.9.jar) Unloaded->Constructed
	ClaySpawn{1.5} [Pam's Clay Spawn] (Pam's Clay Spawn 1.6.4.zip) Unloaded->Constructed
	PluginsforForestry{3.2.30} [PluginsforForestry] (PluginsforForestry-1.6.4-3.2.30.jar) Unloaded->Constructed
	PortalGun{2.0.2} [PortalGun] (PortalGun2.0.2.zip) Unloaded->Constructed
	ProjRed|Compatibility{4.3.5.30} [ProjectRed-Compatibility] (ProjectRedCompat-1.6.4-4.3.5.30.jar) Unloaded->Constructed
	ProjRed|Integration{4.3.5.30} [ProjectRed-Integration] (ProjectRedIntegration-1.6.4-4.3.5.30.jar) Unloaded->Constructed
	ProjRed|Illumination{4.3.5.30} [ProjectRed-Illumination] (ProjectRedLighting-1.6.4-4.3.5.30.jar) Unloaded->Constructed
	QuarryPlus{1.0.0} [QuarryPlus] (QuarryPlus-1.6.4-1.0.3.jar) Unloaded->Constructed
	Redstone Arsenal{1.0.0.0} [Redstone Arsenal] (RedstoneArsenal-1.0.0.0.jar) Unloaded->Constructed
	redstonearmory{pre-dev} [Redstone Armory] (RArm-r1.0-3pre.jar) Unloaded->Constructed
	rcdusts{0.0.6d} [Rock Crusher Metal Dusts Add-On] (RcDusts-0.0.6d.zip) Unloaded->Constructed
	ServerTools{1.6.4 (build 23)} [Server Tools] (Servertools-1.6.4-build23.jar) Unloaded->Constructed
	StevesCarts{2.0.0.b10} [Steve's Carts 2] (stevescarts2.0.0.b10.zip) Unloaded->Constructed
	ThaumicReliquary{1.1.5.TPPI} [Thaumic Reliquary] (ThaumicReliquary-1.1.5.TPPI.jar) Unloaded->Constructed
	TiCTooltips{1.1.5} [TiC Tooltips] (TiCTooltips-mc1.6.4-1.1.5.jar) Unloaded->Constructed
	TMechworks{19.d4b8fa0} [Tinkers' Mechworks] (TMechworks-1.6.4-19.jar) Unloaded->Constructed
	Translocator{1.1.0.15} [Translocator] (Translocator 1.1.0.15.jar) Unloaded->Constructed
	witchery{0.19.2} [Witchery] (witchery-1.6.4-0.19.2.zip) Unloaded->Constructed
	WR-CBE|Core{1.4.0.7} [WR-CBE Core] (wr-cbe 1.4.0.7.jar) Unloaded->Errored
	WR-CBE|Addons{1.4.0.7} [WR-CBE Addons] (wr-cbe 1.4.0.7.jar) Unloaded->Errored
	WR-CBE|Logic{1.4.0.7} [WR-CBE Logic] (wr-cbe 1.4.0.7.jar) Unloaded->Errored
	mod_ZanMinimap{0.9.4} [Zan's Minimap] (zansminimap1.6.4.zip) Unloaded->Constructed
	MineTweaker{1.6.4-2.1.2} [MineTweaker] (ZMineTweaker-1.6.4-2.3.1.jar) Unloaded->Constructed
	FZAddons{0.0.2} [FZAddons] (ZZFZAddons-0.0.2-Fixed.zip) Unloaded->Constructed
	McMultipart{1.0.0.250} [Minecraft Multipart Plugin] (ForgeMultipart-universal-1.6.4-1.0.0.250.jar) Unloaded->Constructed
	ForgeMicroblock{1.0.0.250} [Forge Microblocks] (ForgeMultipart-universal-1.6.4-1.0.0.250.jar) Unloaded->Constructed
	TConstruct Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: gregtech_addon    

when opening it stops at the mojang screen for a minute or two then closes with this in the crash reports i tryed just removing the gregtech_addon and it just closed again 
please help

**Comment by tterrag1098** [comment]
Java 6 is not supported. Update to java 7 or later.

**Comment by justin348** [comment]
im on a school laptop and have no authority to update java is there a way like installing an older version ???

**Comment by tterrag1098** [comment]
No. Your school should update from java 6 anyhow, it's a security risk.
