### ISSUE TITLE
Client crash running TPPI 1.1.2 (cause: botania wand in blood magic altar)

### ISSUE THREAD

**Issue by jacobbridges** [TPPIDev/TestPackPleaseIgnore#636]
Title says it all. I'm running a TPPI server with some friends and I accidentally placed my botania wand into the blood magic altar. My client showed a light blue screen then crashed. I asked another player to retrieve the wand, but when he gets near my home he also crashes.

Any attempts to log back into the game result in crashes, so now we cannot enter the world. (lol?)

I have admin privileges on the server, running no server plugins at the moment. The client crash log is located http://pastebin.com/zk3VVd03. Is there a way to destroy this block with server commands or reset the chunk with server commands? Also, should I report this error to the botania and blood magic mod authors? 

Thanks for reading and any help you can provide. :)

**Comment by TehNut** [comment]
It was a known crash. Botania fixed it in 1.7.10. You need to open the world in MCEdit and delete the offending block at `x - 198`, `y - 124`, `z - 419`.

As for reporting things ever, no. You report to us. *We* report to them. Or, we would if 1.6.4 was not dead on the development side.
