### ISSUE TITLE
version.JSON

### ISSUE THREAD

**Issue by CommunityNetworkMD** [TPPIDev/TestPackPleaseIgnore#637]
Hay everybody,

I have a problem with my MD (Modpack)
everything is OK, but 1 thing not. The version.JSON
![img-20150321-wa0030](https://cloud.githubusercontent.com/assets/11597108/6769295/0cfbbd24-d096-11e4-817b-e246f3f555ce.jpg)

How can i made that? Or have someone that for me?

Greets from Holland!

CommunityNetworkMD

**Comment by TehNut** [comment]
It's not crashing. Don't worry about it.
