### ISSUE TITLE
TPPI won't start!

### ISSUE THREAD

**Issue by PotatoNarwhal** [TPPIDev/TestPackPleaseIgnore#639]
please help! I've tried literally ALMOST everything, but it won't start. I also tried adding more gigs, but I can only go up to one. THIS IS MAKING KAWAII POTATO MAD!!
![__kawaii_potato___by_theakatsumi-d7tsf30 1](https://cloud.githubusercontent.com/assets/11701816/6883876/6aba0646-d591-11e4-8095-90a2006c240e.png)

**Comment by TehNut** [comment]
http://pastebin.com/9rjFNN8v
