### ISSUE TITLE
tppi crashing on mojang screen

### ISSUE THREAD

**Issue by Phillburt** [TPPIDev/TestPackPleaseIgnore#640]
So, i startup the technic launcher, go to modpacks, select and play tppi. from here it loads as normal, gets to the mojang screen, and at the top where it sais Minecraft 1.6.4 it gains the words (Not Responding) ad proceeds to crash.  it worked earlier today and i have no idea whats happening.

Crash Log:  http://paste.ubuntu.com/10905101/

(please tell me if the above link does not work this is my first time with this site)

**Comment by TehNut** [comment]
You have a corrupted Mekanism config. Redownload the pack.
