### ISSUE TITLE
tppi 1.6.4

### ISSUE THREAD

**Issue by soderquist1** [TPPIDev/TestPackPleaseIgnore#645]
i recently got this high end gear with no durability  from thaumcraft i cant remem the name off hand but the legs have an option to produce light around the player. i noticed when ever i have it turned on it make the game laggy and slows it down a lot especially if i have it on at base. also the altar wont craft the lags so i had to  cheat it in and throw away all the components needed to make it.

**Comment by tterrag1098** [comment]
There is nothing we can do about an item being laggy, though this item I've never heard such things before, might just be your computer.

Regardless, this version of the pack is no longer supported anyways, so update to TPPI2.

**Comment by TehNut** [comment]
@tterrag1098 I think it's the Ichor legs. It works the exact same way as Hyperenergetic Nitor. Both are very laggy.

@soderquist1 Hold the legs in your hand and shift right click to disable the ability. There's nothing we can do about it.
