### ISSUE TITLE
Infinite Resource Glitch

### ISSUE THREAD

**Issue by chiefspammer** [TPPIDev/TestPackPleaseIgnore#648]
[Redacted]

**Comment by TehNut** [comment]
1. [Responsible Disclosure](https://en.wikipedia.org/wiki/Responsible_disclosure).

2. TPPI1 is unsupported. We're not going to fix anything in it.

**Comment by chiefspammer** [comment]
I don't like when people answer with lists, and if you read my post you would see that it had already been released somewhere else. I was at least hoping someone would know who to contact because I am not sure if this is a Thermal Expansion bug or a Ender Storage one.

**Comment by TehNut** [comment]
>if you read my post you would see that it had already been released somewhere else.

Does not mean you get/have to publicly disclose it ***more***. 

>it will probably continue to exist because each mod maker would blame the other instead of working to fix it.

No, it will probably continue to exist because it's 1.6.4 and is unsupported.
