### ISSUE TITLE
Modpack minecraft

### ISSUE THREAD

**Issue by zusby** [TPPIDev/TestPackPleaseIgnore#652]
hello there i bought a minecraft server for 8 dollars today, and got my new modpack yesterday, the fact is that i can play singleplayer or in lan but the servers doesn't start, and the modpack must be started from multiMC someone can help me to build the server with the mods at this link? https://mega.nz/#!wo9U2Q5b!AjVXsarDln-IfY0xtJQJ5pPiShH2qulzIopElPGCyLk

**Comment by TehNut** [comment]
This isn't custom pack support.
