### ISSUE TITLE
Extreme lag after updating TPPI2

### ISSUE THREAD

**Issue by Killzone54** [TPPIDev/TestPackPleaseIgnore#654]
I have been playing tppi2 recommended version from the FTB launcher for a week with no problems. I decided to try out 0.2.5 and after loading into the main menu the lag was already 0 to 1 FPS and in game on a new world there is no difference. I have tried allocating more and less ram, using different java commands and reinstalling with no success. After giving up i tried going back to the recommended version and it still works fine. Specs, Cpu: AMD FX-8320, Gpu: ASUS AMD R9 380, and 8 gigs of ram

**Comment by TehNut** [comment]
Install Fastcraft?
